import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/styles.scss";
import { GlobalTheme } from "@carbon/react";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gestion de tareas",
  description: "Generated by create next app - Hemer Meza",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = "g100";
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReactQueryProvider>
          <GlobalTheme theme={theme}>{children}</GlobalTheme>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
